version: 2.1

orbs:
  local:
    executors:
      default:
        docker:
          - image: circleci/node:12

    commands:
      build_test:
        steps:
          - checkout
          - restore_cache:
              keys:
                - &cache_key cache-npm-{{ .Branch }}

          - run:
              name: Install Dependencies
              command: npm ci

          - save_cache:
              key: *cache_key
              paths:
                - ~/.npm

          - run:
              name: Run Test
              command: npm run test

      release:
        steps:
          - run:
              name: Release
              command: npx semantic-release

    jobs:
      default:
        executor: default
        steps:
          - build_test

      master:
        executor: default
        steps:
          - build_test
          - release

workflows:
  main:
    jobs:
      - local/default:
          filters:
            branches:
              ignore:
                - master

      - local/master:
          filters:
            branches:
              only:
                - master
